# Generated by Django 5.1 on 2024-09-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_collection', '0002_alter_datadictionary_data_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.datafile')),
            ],
        ),
    ]
