# Generated by Django 5.1 on 2024-09-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataDictionary',
        ),
    ]
