# Generated by Django 3.2.25 on 2024-06-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='irisdata',
            table='api_iris_data',
        ),
    ]
