# Generated by Django 5.2.18 on 2026-10-10 03:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_lock(apps, schema_editor):
    apps.get_model('execution_jobs', 'QueueLock').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0004_project_projectpolicy_projectartifact_and_more'),
        ('declaration', '0002_add_has_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NativeJob',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('actor_snapshot', models.JSONField()),
                ('authority', models.JSONField()),
                ('specification', models.JSONField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('state', models.CharField(default='queued', max_length=24)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('next_dispatch', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('result', models.JSONField(null=True)),
                ('result_sha256', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='declaration.declaration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=32)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='execution_jobs.nativejob')),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.AddIndex(
            model_name='nativejob',
            index=models.Index(fields=['state', 'next_dispatch'], name='execution_j_state_989d00_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobevent',
            constraint=models.UniqueConstraint(fields=('job', 'revision'), name='job_event_revision_unique'),
        ),
        migrations.RunPython(seed_lock, migrations.RunPython.noop),
    ]
