# Generated by Django 5.1 on 2024-09-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', 'add_original_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.datafile')),
            ],
        ),
    ]
