# Generated by Django 5.1 on 2024-09-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_datadictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionary',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dictionary', to='data_collection.datafile'),
        ),
        migrations.AlterUniqueTogether(
            name='datadictionary',
            unique_together={('data_file', 'column_name')},
        ),
    ]
