# Generated by Django 5.1 on 2024-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_alter_datadictionary_data_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='original_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
