# Generated by Django 5.2.18 on 2026-10-09 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaration', '0002_add_has_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPDatasetGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('read', 'Read'), ('prepare', 'Read and propose')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='MCPAccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('grant_snapshot', models.JSONField(default=dict)),
                ('authority_source', models.CharField(default='stdio_installation_actor', max_length=32)),
                ('file_id', models.PositiveBigIntegerField(null=True)),
                ('operation', models.CharField(max_length=32)),
                ('tool_name', models.CharField(max_length=200)),
                ('required_scope', models.CharField(blank=True, max_length=100)),
                ('arguments_sha256', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(default='started', max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.mcpdatasetgrant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mcpdatasetgrant',
            constraint=models.UniqueConstraint(fields=('actor', 'dataset'), name='mcp_actor_dataset_unique'),
        ),
        migrations.AddIndex(
            model_name='mcpaccessevent',
            index=models.Index(fields=['actor', 'file_id', 'started_at'], name='mcp_access_actor_file_idx'),
        ),
    ]
