# Generated by Django 5.2.18 on 2026-10-09 06:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantActionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('file_id', models.PositiveBigIntegerField()),
                ('action_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('source', models.CharField(default='panel', max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=256)),
                ('context', models.JSONField()),
                ('environment', models.JSONField()),
                ('budget', models.JSONField()),
                ('proposal_sha256', models.CharField(max_length=64)),
                ('state', models.CharField(default='prepared', max_length=24)),
                ('result', models.JSONField(null=True)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(null=True)),
                ('dispatched_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prepared_at'],
                'indexes': [models.Index(fields=['actor', 'file_id', 'prepared_at'], name='assistant_actor_file_idx')],
            },
        ),
    ]
