# Generated by Django 5.2.18 on 2026-10-09 12:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0002_assistantactionapproval"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottleBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("window_started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("blocked_attempts", models.PositiveBigIntegerField(default=0)),
                ("denial_recorded", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SessionAuthority",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("revision", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_snapshot", models.JSONField(default=dict)),
                ("subject_snapshot", models.JSONField(default=dict)),
                ("authority_source", models.CharField(max_length=32)),
                ("event_type", models.CharField(max_length=32)),
                ("outcome", models.CharField(default="pending", max_length=24)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("source_key", models.CharField(blank=True, max_length=64)),
                ("principal_key", models.CharField(blank=True, max_length=64)),
                ("session_revision", models.UUIDField(null=True)),
                ("operator_label", models.CharField(blank=True, max_length=100)),
                ("request_sha256", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["actor", "started_at"], name="auth_event_actor_time_idx"),
                    models.Index(fields=["event_type", "started_at"], name="auth_event_type_time_idx"),
                ],
            },
        ),
    ]
