# Generated by Django 5.2.18 on 2026-10-09 15:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_loginthrottlebucket_sessionauthority_and_more'),
        ('declaration', '0002_add_has_header'),
        ('modeling', '0003_holdout_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('path_sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('relative_path', models.TextField()),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declaration.declaration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAuthorityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('authority_source', models.CharField(max_length=40)),
                ('operator_label', models.CharField(blank=True, max_length=100)),
                ('operation', models.CharField(max_length=40)),
                ('resource', models.JSONField(default=dict)),
                ('outcome', models.CharField(max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('request_sha256', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDataset',
            fields=[
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_binding', serialize=False, to='declaration.declaration')),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPipeline',
            fields=[
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_binding', serialize=False, to='modeling.pipelinerun')),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('reviewer', 'Reviewer'), ('admin', 'Project administrator')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='access_control.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'actor'), name='project_actor_unique')],
            },
        ),
    ]
