# Generated by Django 5.1.15 on 2026-03-25 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pipeline_type', models.CharField(default='boosting', max_length=50)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('current_step', models.CharField(choices=[('declaration', 'Declaration'), ('preprocessing', 'Preprocessing'), ('data_quality', 'Data Quality'), ('modeling', 'Modeling'), ('sfs', 'SFS'), ('evaluation', 'Evaluation'), ('deployment', 'Deployment')], default='declaration', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
