# Generated by Django 5.2.18 on 2026-10-09 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_holdoutaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holdoutaccess',
            name='actor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='holdoutaccess',
            name='attempt_state',
            field=models.CharField(default='historical_unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='holdoutaccess',
            name='holdout_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='holdoutaccess',
            name='holdout_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='holdoutaccess',
            index=models.Index(fields=['dataset_sha256', 'holdout_key'], name='holdout_source_key_idx'),
        ),
    ]
