# Generated by Django 5.2.18 on 2026-10-09 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0004_project_projectpolicy_projectartifact_and_more'),
        ('declaration', '0002_add_has_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_id', models.UUIDField()),
                ('execution_id', models.UUIDField()),
                ('assessment_id', models.UUIDField()),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('context_sha256', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='declaration.declaration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.project')),
            ],
        ),
        migrations.CreateModel(
            name='PackageReviewEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('actor_snapshot', models.JSONField()),
                ('authority_snapshot', models.JSONField()),
                ('request_sha256', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=24)),
                ('finding_id', models.UUIDField(null=True)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='deployment.packagereview')),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.AddConstraint(
            model_name='packagereview',
            constraint=models.UniqueConstraint(fields=('dataset', 'bundle_id'), name='review_dataset_bundle_unique'),
        ),
        migrations.AddConstraint(
            model_name='packagereviewevent',
            constraint=models.UniqueConstraint(fields=('review', 'revision'), name='review_event_revision_unique'),
        ),
    ]
