# Generated by Django 5.2.18 on 2026-10-10 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
        ('execution_jobs', '0002_nativejob_source_dataset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereviewevent',
            name='evidence',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='packagereviewevent',
            name='evidence_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='execution_jobs.nativejob'),
        ),
        migrations.AddConstraint(
            model_name='packagereviewevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence__isnull', True), ('evidence_job__isnull', True)), models.Q(('evidence__isnull', False), ('evidence_job__isnull', False)), _connector='OR'), name='review_event_evidence_pair'),
        ),
    ]
