# Generated by Django 5.1 on 2024-09-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='declaration/')),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dictionary', to='declaration.declaration')),
            ],
            options={
                'unique_together': {('declaration', 'column_name')},
            },
        ),
    ]
