# Generated by Django 5.1.15 on 2026-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='has_header',
            field=models.BooleanField(default=True),
        ),
    ]
